
# uv.system.starter.noexist=Det finns data tillgänglig via Workshop-tillägg som inte finns i spelets data-mapp.\nVill du importera dem till din data-mapp?

# uv.system.starter.replace=Det finns data tillgänglig via Workshop-tillägg som har samma namn men med annat innehåll i spelets data-mapp.\nVill du importera dem igen och ersätta dem som finns i din data-mapp?

